#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/database

- name: Run database container
  docker_container:
    name: db-student
    image: chiaracarlino/tp-devops-simple-api-database:latest
    state: started
    restart_policy: always
    env:
      POSTGRES_USER: "{{ db_user }}"
      POSTGRES_PASSWORD: "{{ db_password }}"
      POSTGRES_DB: "{{ db_name }}"
    networks:
      - name: app-network
    volumes:
      - /opt/db_data:/var/lib/postgresql/data
